# Generated by Django 4.0.4 on 2022-05-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=128, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('plus_one', models.BooleanField(default=False)),
                ('song', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
